### ISSUE TITLE
EVRE_v1.01 - "Modlist is corrupt" Error

### ISSUE THREAD

**Issue by Rorgy** [Ashok0/EnderalVREssentials#1]
When I open up the new wabbajack file it wont let me start the install due to this error:

Modlist is corrupt: Error resolving type specified in JSON 'TransformedTexture, Wabbajack.Lib'.
Path 'Directives[9337].$type', line 1, position 2165106.

**Comment by Ashok0** [comment]
Have you tried redownloading the file?  I redownloaded v1.01 directly from the Github server and it ran without any errors.

**Comment by Rorgy** [comment]
I downloaded the newest version of Wabbajack (2.5.0.4) and it worked!
