### ISSUE TITLE
Hero Menu

### ISSUE THREAD

**Issue by kraoro** [Ashok0/EnderalVREssentials#10]
When I open the Hero Menu using gestures, I can't interact with it in any way. I can't level up skills, etc. The only thing I can do is close the Hero menu, and even then that only sometimes works and I end up closing the menu with Escape on my computer keyboard.

**Comment by Ashok0** [comment]
The hero menu is just a list of stats.  There is actually nothing to interact with.  To level up, you have to use the stones in the Meditation area.
