### ISSUE TITLE
Introduction cutscene doesn't work

### ISSUE THREAD

**Issue by ViolentSempie** [Ashok0/EnderalVREssentials#3]
I'm getting a steamVR loading screen with audio from the introduction cutscene. After the cutscene is done, the game loads fine.

**Comment by Ashok0** [comment]
Hi, this is a known problem which is noted in both the Enderal VR and Wabbajack documentation and there is no fix.  There are only 3 cutscenes in the game.  You can view them from your \mods\Enderal SE\Video\ folder using a video player of your choice i.e. VLC.

**Comment by ViolentSempie** [comment]
Yeah mb just read all the known issues
