### ISSUE TITLE
Pressing the grip button stops dialog and won't let me start the dialog again in the beginning

### ISSUE THREAD

**Issue by ViolentSempie** [Ashok0/EnderalVREssentials#4]
I haven't been able to start the game yet as whenever I'm in the beginning talking to daddy, I accidently tap the grip button, which leaves the dialog. After this, I'm unable to start the dialog again.

This has me restarting the game a few times before I gave up as I was still fiddling with settings and other things. I don't know if this is an issue that happens further into the game, might just be in the beginning but I think it's because you get locked in place for these specific dialogs and when you cancel them you don't get the option to talk to them again.

**Comment by Ashok0** [comment]
Hi, the dialog glitch with the grip buttons soft locking the game is a known issue which is noted in both the Enderal VR and Wabbajack documentation.  There is no fix at this time, it's best to save often in case you accidently cancel dialogue prematurely.
