### ISSUE TITLE
Invisible dragon at Dragon Aerie?

### ISSUE THREAD

**Issue by admiralzeech** [Ashok0/EnderalVREssentials#5]
Hi, I went to the Dragon Aerie near Riverville, and the Dragon was invisible?  I could fight and kill it, and it would breath fire and fly around.  But completely invisible.

Does this occur for you?

**Comment by admiralzeech** [comment]
I was able to solve this issue by disabling the Dragon replacer mod.  Did it replace the wrong dragon type or something?

**Comment by Ashok0** [comment]
It seems the dragon replacer mod is not working properly. I'll remove the mod from the Wabbajack list with the next update.  Closing this issue as it appears to be solved.
