### ISSUE TITLE
Dear Diary Mod configuration causes russian symbols on German translation

### ISSUE THREAD

**Issue by Johann-Foerster** [Ashok0/EnderalVREssentials#7]
I am trying to get the German language pack running, but the current configuration of the dear diary mod causes russian symbols to appear instead of german umlauts (ä,ö,ü,ß,...), see screenshot (marked yellow). When I run the installer (reinstall mod in mod organizer) and select the Latin / ENG font in the very last menu, the umlauts are displayed correctly. However, this breaks the favorites / items menu, i.e. it transforms it to a very tall, unreadable column. Using the backup & restore functionality and the installer several times, I was still not able to reach the initial settings of the mod but just replacing the font; so either the umlauts break or the items/favorites menus. How exactly was the mod set up for the wabbajack release? Is it possible to replace just the font and nothing else for german umlauts? Any help is highly appreciated

![LangErr](https://user-images.githubusercontent.com/37768526/126871262-6f5e3a57-d55c-44ad-88f6-f4ba9ea912e5.png)

**Comment by Ashok0** [comment]
Hi, Dear Diary is an optional mod that can be safely disabled by unticking "Dear Diary VR - Paper SkyUI and Categorized Favorites" from the left window pane if you want to use the vanilla SkyUI interface instead.   I'm not sure if the vanilla interface plays better with the German language pack versus the Dear Diary UI, it's worth a shot if you are unable to get Dear Diary working.

Regarding Dear Diary, you need to initially install it using the VR version.  Go to the Downloads tab, the right click "Dear Diary VR - Paper SkyUI and Categorized Favorites-44874-1-06-1617397007.zip" and hit Install.   Recommended install settings are: Dear Diary VR > None > Rollover Menu Fix - MoreHUD VR > None > (On the next screen, you can experiment with enabling or disabling the Sovngarde font.  I don't know which is best for the German language pack but I disabled it for the Wabbajack release.)  > Install > REPLACE (if prompted).

Once you have the base Dear Diary VR mod installed, you need to patch it for Enderal SE.   Go to the Downloads tab, then right click "Dear Diary-112-3-0-5-1624174013.zip" and hit Install.  Recommended install settings are:  Select NO and NONE for everything except "Install Tab Menu replacer" which must be set to YES, "Replace the cursor?" which can be set to your quill of choice (I use "Dark red quill"), and "Replace the main font?" which is set to No for the Wabbajack release but for German may need to be set to "ENG (Latin)".  On the final page with the Install button, you can leave the Name as "Dear Diary" and click "Install" to install the Enderal SE patch as a new mod called "Dear Diary" which needs to be placed below "Dear Diary VR" in the Mod Organizer 2 left window pane.  Or you can change the Name field to:  "Dear Diary VR - Paper SkyUI and Categorized Favorites" and then click Install > MERGE to merge the Enderal SE patch with Dear Diary VR.  

I hope that all makes sense!  Let me know if that resolves the issue or if you have any further questions.

**Comment by Johann-Foerster** [comment]
I followed your steps and selected ENG (Latin) in the end, and it is perfect now. Thanks alot!! Paper UI adds a lot of immersion for me, thus I am very glad it works now ;)
