### ISSUE TITLE
Character gets stuck when smoking peaceweed

### ISSUE THREAD

**Issue by admiralzeech** [Ashok0/EnderalVREssentials#8]
Hi, when you try to smoke peaceweed with a pipe, you character sits down and you get a prompt to press any directional key to exit.  However, trying to move with motion controllers doesn't seem to exit, and none of the controller buttons work, apart from bringing up the menu and loading a save game, which seems the only way to exit this state.

I'm playing on Quest 2 with Virtual Desktop.

**Comment by Ashok0** [comment]
Hi, can you provide me with a saved game?  If you can email it to ashok0@gmail.com or provide me with MEGA or Google Drive links here, I would love to look into this issue further!

**Comment by formaldehydeson** [comment]
newest version of enderal vr has a fix for this, you can update it in your MO2 
https://www.nexusmods.com/enderalspecialedition/mods/8

**Comment by Ashok0** [comment]
I have updated the Wabbajack to v1.103.  This release uses Enderal SE v2.0.9 which fixes the peaceweed smoking bug.
