### ISSUE TITLE
Error message, REL/Relocation.h(462) failed to obtain module handle

### ISSUE THREAD

**Issue by VijuaruKei** [Ashok0/EnderalVREssentials#9]
Hello, I installed everything according to the guide, but I can't launch the game, I get this error everytime I launch SKSE

REL/Relocation.h(462) failed to obtain module handle

It seems tied to the Spell Perk Item Distributor mod, I haven't found a way to get this working, any help ?

Thanks in advance

**Comment by Ashok0** [comment]
Hi, I just updated the Wabbajack to v1.103 which uses the new Spell Perk Item Distributor (SPID) VR mod from alandtse.  If you redownload the Wabbajack, all SPID issues should be resolved.
